// import type { FooterItem, MainNavItem } from "@/types"
//
// import { productCategories } from "@/config/products"
// import { slugify } from "@/lib/utils"

import { Icons } from '@/components/icons';
import { env } from '@/env.mjs';

export type SiteConfig = typeof siteConfig;

export const siteConfig = {
  name: env.NEXT_PUBLIC_SITE_NAME,
  author: env.NEXT_PUBLIC_AUTHOR_NAME,
  slogan: 'Watch Movies & TV Shows Online Free.',
  description:
    'Watch movies & TV shows online or stream right to your smart TV, game console, PC, Mac, mobile, tablet and more for free.',
  keywords: [
    'watch movies',
    'movies online',
    'watch TV',
    'TV online',
    'Movie website',
    'TV shows online',
    'watch TV shows',
    'stream movies',
    'stream tv',
    'instant streaming',
    'watch online',
    'movies',
    'watch TV online',
    'no download',
    'full length movies',
    'Micorp Movies',
    'CCR8',
    'Free Movies',
    'Movie streaming sites',
    'Free Movie Streaming',
    'Watch Movies Online',
    'Watch TV Shows Online',
    'Free Movie Websites',
    'Free Movie Sites',
    'Free Movie Streaming Sites',
    'Free Movies Online',
    'Free Movie Streaming Websites',
    'online movie streaming',
    'streaming movies',
    'watch movies online free',
    'watch TV shows online free',
    'stream TV shows',
    'free streaming',
    'watch free movies',
    'watch free TV shows',
    'streaming platforms',
    'movie websites',
    'TV show websites',
    'streaming services',
    'watch movies in HD',
    'watch TV shows in HD',
    'watch movies on mobile',
    'watch TV shows on mobile',
    'watch movies on tablet',
    'watch TV shows on tablet',
    'watch movies on smart TV',
    'watch TV shows on smart TV',
    'watch movies on PC',
    'watch TV shows on PC',
    'watch movies on Mac',
    'watch TV shows on Mac',
    'watch movies on game console',
    'watch TV shows on game console',
    'watch movies without download',
    'watch movies for free',
    'watch TV shows for free',
    'best movie streaming sites',
    'best TV show streaming sites',
    'top movie streaming sites',
    'top TV show streaming sites',
    'popular movie streaming sites',
    'popular TV show streaming sites',
    'latest movies',
    'latest TV shows',
    'new movies',
    'new TV shows',
    'trending movies',
    'trending TV shows',
    'recommended movies',
    'recommended TV shows',
    'personalized recommendations',
    'movie genres',
    'TV show genres',
    'action movies',
    'comedy movies',
    'drama movies',
    'horror movies',
    'romantic movies',
    'sci-fi movies',
    'thriller movies',
    'adventure movies',
    'animated movies',
    'documentary movies',
    'fantasy movies',
    'family movies',
    'crime movies',
    'mystery movies',
    'superhero movies',
    'historical movies',
    'western movies',
    'war movies',
    'musical movies',
    'biography movies',
    'sports movies',
    'reality TV shows',
    'drama TV shows',
    'comedy TV shows',
    'action TV shows',
    'thriller TV shows',
    'horror TV shows',
    'sci-fi TV shows',
    'fantasy TV shows',
    'crime TV shows',
    'mystery TV shows',
    'romantic TV shows',
    'historical TV shows',
    'animated TV shows',
    'reality competition shows',
    'talk shows',
    'game shows',
    'variety shows',
    'late night shows',
    'news shows',
    'educational shows',
    'kids shows',
    'cartoons',
    'anime',
    'foreign movies',
    'foreign TV shows',
    'international movies',
    'international TV shows',
    'award-winning movies',
    'award-winning TV shows',
    'classic movies',
    'classic TV shows',
    'cult movies',
    'cult TV shows',
    'independent movies',
    'independent TV shows',
    'blockbuster movies',
    'box office movies',
    'box office TV shows',
    'critically acclaimed movies',
    'critically acclaimed TV shows',
    'Oscar-winning movies',
    'Emmy-winning TV shows',
    'Golden Globe-winning movies',
    'Golden Globe-winning TV shows',
    'top-rated movies',
    'top-rated TV shows',
    'highest-grossing movies',
    'highest-rated movies',
    'highest-rated TV shows',
    'best-reviewed movies',
    'best-reviewed TV shows',
    'must-watch movies',
    'must-watch TV shows',
    'binge-worthy TV shows',
    'culturally significant movies',
    'culturally significant TV shows',
    'cult classics',
    'hidden gems',
    'underrated movies',
    'underrated TV shows',
    'upcoming movies',
    'upcoming TV shows',
    'movie recommendations',
    'TV show recommendations',
    'movie suggestions',
    'TV show suggestions',
    'movie lovers',
    'TV show enthusiasts',
    'film buffs',
    'binge-watchers',
    'streaming enthusiasts',
    'entertainment',
    'movies and TV shows',
    'streaming library',
    'watchlist',
    'entertainment news',
    'movie trivia',
    'TV show trivia',
    'behind the scenes',
    'movie facts',
    'TV show facts',
    'movie quotes',
    'TV show quotes',
    'movie reviews',
    'TV show reviews',
    'movie ratings',
    'TV show ratings',
    'movie news',
    'TV show news',
    'movie trailers',
    'TV show trailers',
    'movie recommendations',
    'TV show recommendations',
    'movie suggestions',
    'TV show suggestions',
    'movie discussions',
    'TV show discussions',
    'movie community',
    'TV show community',
    'movie fans',
    'TV show fans',
    'movie blog',
    'TV show blog',
    'movie podcast',
    'TV show podcast',
    'movie analysis',
    'TV show analysis',
    'movie theories',
    'TV show theories',
    'movie quizzes',
    'TV show quizzes',
    'movie quizzes',
    'TV show quizzes',
    'movie merchandise',
    'TV show merchandise',
    'movie posters',
    'TV show posters',
    'movie memorabilia',
    'TV show memorabilia',
    'movie collectibles',
    'TV show collectibles',
    'movie gifts',
    'TV show gifts',
    'movie streaming',
    'TV show streaming',
    'watch movies online',
    'watch TV shows online',
    'stream movies online',
    'stream TV shows online',
    'free movie streaming',
    'free TV show streaming',
    'watch movies for free',
    'watch TV shows for free',
    'movie streaming platforms',
    'TV show streaming platforms',
    'best movie streaming platforms',
    'best TV show streaming platforms',
    'top movie streaming platforms',
    'top TV show streaming platforms',
    'popular movie streaming platforms',
    'popular TV show streaming platforms',
    'streaming services for movies',
    'streaming services for TV shows',
    'streaming services for free',
    'streaming services for movies and TV shows',
    'streaming services for binge-watching',
    'streaming services for entertainment',
    'streaming services for film lovers',
    'streaming services for TV show enthusiasts',
    'streaming services for movie buffs',
    'streaming services for binge-watchers',
    'streaming services for streaming enthusiasts',
    'streaming services for entertainment news',
    'streaming services for movie trivia',
    'streaming services for TV show trivia',
    'streaming services for behind the scenes',
    'streaming services for movie facts',
    'streaming services for TV show facts',
    'streaming services for movie quotes',
    'streaming services for TV show quotes',
    'streaming services for movie reviews',
    'streaming services for TV show reviews',
    'streaming services for movie ratings',
    'streaming services for TV show ratings',
    'streaming services for movie news',
    'streaming services for TV show news',
    'streaming services for movie trailers',
    'streaming services for TV show trailers',
    'streaming services for movie recommendations',
    'streaming services for TV show recommendations',
    'streaming services for movie suggestions',
    'streaming services for TV show suggestions',
    'streaming services for movie discussions',
    'streaming services for TV show discussions',
    'streaming services for movie community',
    'streaming services for TV show community',
    'streaming services for movie fans',
    'streaming services for TV show fans',
    'streaming services for movie blog',
    'streaming services for TV show blog',
    'streaming services for movie podcast',
    'streaming services for TV show podcast',
    'streaming services for movie analysis',
    'streaming services for TV show analysis',
    'streaming services for movie theories',
    'streaming services for TV show theories',
    'streaming services for movie quizzes',
    'streaming services for TV show quizzes',
    'streaming services for movie quizzes',
    'streaming services for TV show quizzes',
    'streaming services for movie merchandise',
    'streaming services for TV show merchandise',
    'streaming services for movie posters',
    'streaming services for TV show posters',
    'streaming services for movie memorabilia',
    'streaming services for TV show memorabilia',
    'streaming services for movie collectibles',
    'streaming services for TV show collectibles',
    'streaming services for movie gifts',
    'streaming services for TV show gifts',
    'stream movies in HD',
    'stream TV shows in HD',
    'watch movies on mobile',
    'watch TV shows on mobile',
    'watch movies on tablet',
    'watch TV shows on tablet',
    'watch movies on smart TV',
    'watch TV shows on smart TV',
    'watch movies on PC',
    'watch TV shows on PC',
    'watch movies on Mac',
    'watch TV shows on Mac',
    'watch movies on game console',
    'watch TV shows on game console',
    'watch movies without download',
    'watch movies for free',
    'watch TV shows for free',
    'best movie streaming sites',
    'best TV show streaming sites',
    'top movie streaming sites',
    'top TV show streaming sites',
    'popular movie streaming sites',
    'popular TV show streaming sites',
    'latest movies',
    'latest TV shows',
    'new movies',
    'new TV shows',
    'trending movies',
    'trending TV shows',
    'recommended movies',
    'recommended TV shows',
    'personalized recommendations',
    'movie genres',
    'TV show genres',
    'action movies',
    'comedy movies',
    'drama movies',
    'horror movies',
    'romantic movies',
    'sci-fi movies',
    'thriller movies',
    'adventure movies',
    'animated movies',
    'documentary movies',
    'fantasy movies',
    'family movies',
    'crime movies',
    'mystery movies',
    'superhero movies',
    'historical movies',
    'western movies',
    'war movies',
    'musical movies',
    'biography movies',
    'sports movies',
    'reality TV shows',
    'drama TV shows',
    'comedy TV shows',
    'action TV shows',
    'thriller TV shows',
    'horror TV shows',
    'sci-fi TV shows',
    'fantasy TV shows',
    'crime TV shows',
    'mystery TV shows',
    'romantic TV shows',
    'historical TV shows',
    'animated TV shows',
    'reality competition shows',
    'talk shows',
    'game shows',
    'variety shows',
    'late night shows',
    'news shows',
    'educational shows',
    'kids shows',
    'cartoons',
    'anime',
    'foreign movies',
    'foreign TV shows',
    'international movies',
    'international TV shows',
    'award-winning movies',
    'award-winning TV shows',
    'classic movies',
    'classic TV shows',
    'cult movies',
    'cult TV shows',
    'independent movies',
    'independent TV shows',
    'blockbuster movies',
    'box office movies',
    'box office TV shows',
    'critically acclaimed movies',
    'critically acclaimed TV shows',
    'Oscar-winning movies',
    'Emmy-winning TV shows',
    'Golden Globe-winning movies',
    'Golden Globe-winning TV shows',
    'top-rated movies',
    'top-rated TV shows',
    'highest-grossing movies',
    'highest-rated movies',
    'highest-rated TV shows',
    'best-reviewed movies',
    'best-reviewed TV shows',
    'must-watch movies',
    'must-watch TV shows',
    'binge-worthy TV shows',
    'culturally significant movies',
    'culturally significant TV shows',
    'cult classics',
    'hidden gems',
    'underrated movies',
    'underrated TV shows',
    'upcoming movies',
    'upcoming TV shows',
    'movie recommendations',
    'TV show recommendations',
    'movie suggestions',
    'TV show suggestions',
    'movie lovers',
    'TV show enthusiasts',
    'film buffs',
    'binge-watchers',
    'streaming enthusiasts',
    'entertainment',
    'movies and TV shows',
    'streaming library',
    'watchlist',
    'entertainment news',
    'movie trivia',
    'TV show trivia',
    'behind the scenes',
    'movie facts',
    'TV show facts',
    'movie quotes',
    'TV show quotes',
    'movie reviews',
    'TV show reviews',
    'movie ratings',
    'TV show ratings',
    'movie news',
    'TV show news',
    'movie trailers',
    'TV show trailers',
    'movie recommendations',
    'TV show recommendations',
    'movie suggestions',
    'TV show suggestions',
    'movie discussions',
    'TV show discussions',
    'movie community',
    'TV show community',
    'movie fans',
    'TV show fans',
    'movie blog',
    'TV show blog',
    'movie podcast',
    'TV show podcast',
    'movie analysis',
    'TV show analysis',
    'movie theories',
    'TV show theories',
    'movie quizzes',
    'TV show quizzes',
    'movie quizzes',
    'TV show quizzes',
    'movie merchandise',
    'TV show merchandise',
    'movie posters',
    'TV show posters',
    'movie memorabilia',
    'TV show memorabilia',
    'movie collectibles',
    'TV show collectibles',
    'movie gifts',
    'TV show gifts',
    'movie streaming',
    'TV show streaming',
    'watch movies online',
    'watch TV shows online',
    'stream movies online',
    'stream TV shows online',
    'free movie streaming',
    'free TV show streaming',
    'watch movies for free',
    'watch TV shows for free',
    'movie streaming platforms',
    'TV show streaming platforms',
    'best movie streaming platforms',
    'best TV show streaming platforms',
    'top movie streaming platforms',
    'top TV show streaming platforms',
    'popular movie streaming platforms',
    'popular TV show streaming platforms',
    'streaming services for movies',
    'streaming services for TV shows',
    'streaming services for free',
    'streaming services for movies and TV shows',
    'streaming services for binge-watching',
    'streaming services for entertainment',
    'streaming services for film lovers',
    'streaming services for TV show enthusiasts',
    'streaming services for movie buffs',
    'streaming services for binge-watchers',
    'streaming services for streaming enthusiasts',
    'streaming services for entertainment news',
    'streaming services for movie trivia',
    'streaming services for TV show trivia',
    'streaming services for behind the scenes',
    'streaming services for movie facts',
    'streaming services for TV show facts',
    'streaming services for movie quotes',
    'streaming services for TV show quotes',
    'streaming services for movie reviews',
    'streaming services for TV show reviews',
    'streaming services for movie ratings',
    'streaming services for TV show ratings',
    'streaming services for movie news',
    'streaming services for TV show news',
    'streaming services for movie trailers',
    'streaming services for TV show trailers',
    'streaming services for movie recommendations',
    'streaming services for TV show recommendations',
    'streaming services for movie suggestions',
    'streaming services for TV show suggestions',
    'streaming services for movie discussions',
    'streaming services for TV show discussions',
    'streaming services for movie community',
    'streaming services for TV show community',
    'streaming services for movie fans',
    'streaming services for TV show fans',
    'streaming services for movie blog',
    'streaming services for TV show blog',
    'streaming services for movie podcast',
    'streaming services for TV show podcast',
    'streaming services for movie analysis',
    'streaming services for TV show analysis',
    'streaming services for movie theories',
    'streaming services for TV show theories',
    'streaming services for movie quizzes',
    'streaming services for TV show quizzes',
    'streaming services for movie quizzes',
    'streaming services for TV show quizzes',
    'streaming services for movie merchandise',
    'streaming services for TV show merchandise',
    'streaming services for movie posters',
    'streaming services for TV show posters',
    'streaming services for movie memorabilia',
    'streaming services for TV show memorabilia',
    'streaming services for movie collectibles',
    'streaming services for TV show collectibles',
    'streaming services for movie gifts',
    'streaming services for TV show gifts',
    'stream movies in HD',
    'stream TV shows in HD',
    'watch movies on mobile',
    'watch TV shows on mobile',
    'watch movies on tablet',
    'watch TV shows on tablet',
    'watch movies on smart TV',
    'watch TV shows on smart TV',
    'watch movies on PC',
    'watch TV shows on PC',
    'watch movies on Mac',
    'watch TV shows on Mac',
    'watch movies on game console',
    'watch TV shows on game console',
    'watch movies without download',
    'watch movies for free',
    'watch TV shows for free',
    'best movie streaming sites',
    'best TV show streaming sites',
    'top movie streaming sites',
    'top TV show streaming sites',
    'popular movie streaming sites',
    'popular TV show streaming sites',
    'latest movies',
    'latest TV shows',
    'new movies',
    'new TV shows',
    'trending movies',
    'trending TV shows',
    'recommended movies',
    'recommended TV shows',
    env.NEXT_PUBLIC_SITE_NAME,
  ],
  url: env.NEXT_PUBLIC_APP_URL,
  ogImage: `${env.NEXT_PUBLIC_APP_URL}/images/hero.jpg`,
  links: {
    twitter: `${env.NEXT_PUBLIC_TWITTER}`,
    insta: `${env.NEXT_PUBLIC_INSTAGRAM}`,
    github: 'https://github.com/ChasteCR8',
    githubAccount: '',
  },
  socialLinks: [
    {
      title: 'Facebook',
      href: `${env.NEXT_PUBLIC_FACEBOOK}`,
      icon: Icons.facebook,
    },
    {
      title: 'Instagram',
      href: `${env.NEXT_PUBLIC_INSTAGRAM}`,
      icon: Icons.instagram,
    },
    {
      title: 'Twitter',
      href: `${env.NEXT_PUBLIC_TWITTER}`,
      icon: Icons.twitter,
    },
    {
      title: 'Youtube',
      href: `${env.NEXT_PUBLIC_YOUTUBE}`,
      icon: Icons.youtube,
    },
  ],
  footerItems: [
    // { title: 'Audio Description', href: '/' },
    // { title: 'Help Center', href: '/' },
    // { title: 'Gift Cards', href: '/' },
    // { title: 'Media Center', href: '/' },
    // { title: 'Investor Relations', href: '/' },
    // { title: 'Jobs', href: '/' },
    { title: 'Terms of Use', href: '/terms-of-use' },
    { title: 'Privacy', href: '/' },
    { title: 'Legal Notices', href: '/' },
    // { title: 'Cookie Preferences', href: '/' },
    // { title: 'Corporate Information', href: '/' },
    { title: 'Contact Us', href: '/' },
  ],
  mainNav: [
    {
      title: 'Home',
      href: '/home',
      // icon: Icons.play,
    },
    {
      title: 'TV Shows',
      href: '/tv-shows',
      // icon: Icons.tvShow,
    },
    {
      title: 'Movies',
      href: '/movies',
      // icon: Icons.movie,
    },
    {
      title: 'New & Popular',
      href: '/new-and-popular',
      // icon: Icons.trendingUp,
    },
    // {
    //   title: "My List",
    //   href: "/my-list",
    //   // icon: Icons.list,
    // },
    {
      title: 'Notifications',
      // onClick: () => alert("🛹 Do a kickflip"),
      // icon: Icons.bell,
    },
  ],
};
